PATCH /api/2.3/tenders/d5f01806d85143458795cbd133b0e667/cancellations/87abd9e46bc14a34858fa1ccc1071006?acc_token=f945406a1ac44cff8f49754d54f658fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5f01806d85143458795cbd133b0e667/cancellations/87abd9e46bc14a34858fa1ccc1071006/documents/6b30ada17f704b2cb64a3792d99c8b2d?download=e3afa4897ade4ee1882b58374d737500", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-24T18:20:59.825782+03:00", 
        "id": "6b30ada17f704b2cb64a3792d99c8b2d", 
        "dateModified": "2017-06-24T18:20:59.825838+03:00"
      }, 
      {
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5f01806d85143458795cbd133b0e667/cancellations/87abd9e46bc14a34858fa1ccc1071006/documents/6b30ada17f704b2cb64a3792d99c8b2d?download=802e095b60844994b4469c535cf1e7ca", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-24T18:20:59.825782+03:00", 
        "id": "6b30ada17f704b2cb64a3792d99c8b2d", 
        "dateModified": "2017-06-24T18:21:00.317750+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2017-06-24T18:21:00.505993+03:00", 
    "cancellationOf": "tender", 
    "id": "87abd9e46bc14a34858fa1ccc1071006"
  }
}

