PATCH /api/2.3/tenders/d5f01806d85143458795cbd133b0e667/questions/c616c4905e7d481da326b4de16c00df4?acc_token=f945406a1ac44cff8f49754d54f658fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2017-06-24T18:20:56.627386+03:00", 
    "title": "Калорійність", 
    "date": "2017-06-24T18:20:56.553152+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "c616c4905e7d481da326b4de16c00df4", 
    "questionOf": "tender"
  }
}

