PATCH /api/2.3/tenders/fcc7868335f744eb82e1870d6ed5f9e4/awards/0d1b966adfc64b679846d7a835008770/complaints/fe1a325a84a948aa892ad2fdc8b5fe24?acc_token=364725f3ffb548aeb0b4743a85b5d853 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopping", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2016-07-25T16:58:13.906257+03:00", 
    "dateAccepted": "2016-07-25T16:58:11.383436+03:00", 
    "dateSubmitted": "2016-07-25T16:58:08.317404+03:00", 
    "complaintID": "UA-2016-07-25-000001.4", 
    "date": "2016-07-25T16:58:13.918111+03:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "fe1a325a84a948aa892ad2fdc8b5fe24"
  }
}

