GET /api/2.3/tenders/fcc7868335f744eb82e1870d6ed5f9e4/awards/0d1b966adfc64b679846d7a835008770/complaints/4d91e591bf9046eb999fa12c9c0e9248 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2016-07-25T16:58:12.237306+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/fcc7868335f744eb82e1870d6ed5f9e4/awards/0d1b966adfc64b679846d7a835008770/complaints/4d91e591bf9046eb999fa12c9c0e9248/documents/bfe9a28b58974a49a01e9f8c5bc201a4?download=1e6fe41a721040a7b79d697a5d0a2b1f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-25T16:58:07.589512+03:00", 
        "id": "bfe9a28b58974a49a01e9f8c5bc201a4", 
        "dateModified": "2016-07-25T16:58:07.589547+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/fcc7868335f744eb82e1870d6ed5f9e4/awards/0d1b966adfc64b679846d7a835008770/complaints/4d91e591bf9046eb999fa12c9c0e9248/documents/9e25c81cbf8e4176b1718820564f95f3?download=5a9dbeb06d6448c7bdc7e22f4fade078", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-25T16:58:11.956888+03:00", 
        "id": "9e25c81cbf8e4176b1718820564f95f3", 
        "dateModified": "2016-07-25T16:58:11.956923+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2016-07-25T16:58:10.861954+03:00", 
    "dateSubmitted": "2016-07-25T16:58:07.762167+03:00", 
    "complaintID": "UA-2016-07-25-000001.1", 
    "date": "2016-07-25T16:58:12.250514+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "4d91e591bf9046eb999fa12c9c0e9248"
  }
}

