PATCH /api/2.3/tenders/d5f01806d85143458795cbd133b0e667/bids/b94deeb4edae4cdb8e6571b1b455abfb?acc_token=cf643c97d1f84f4487a651ad8d5e11da HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/d5f01806d85143458795cbd133b0e667/bids/b94deeb4edae4cdb8e6571b1b455abfb/documents/aa82c54ea2684536a144db1e31a50111?download=025f32aa28fb48a1bb60e8ae4d7f4d00", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-24T18:20:57.249657+03:00", 
        "id": "aa82c54ea2684536a144db1e31a50111", 
        "dateModified": "2017-06-24T18:20:57.249688+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "b94deeb4edae4cdb8e6571b1b455abfb", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-06-24T18:20:57.097741+03:00", 
    "selfQualified": true
  }
}

