GET /api/2.3/tenders/0fe104c59a26455cb75251cb8786cfde/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2017-06-24T18:20:53.555431+03:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/0fe104c59a26455cb75251cb8786cfde/complaints/767b8633d3a74e46b7e3c8ef54d4de80/documents/1597f48002954ac99e8df05565215cf4?download=1c982a1335dc4888a83e5159279b539e", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-06-24T18:20:51.358802+03:00", 
          "id": "1597f48002954ac99e8df05565215cf4", 
          "dateModified": "2017-06-24T18:20:51.358841+03:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/0fe104c59a26455cb75251cb8786cfde/complaints/767b8633d3a74e46b7e3c8ef54d4de80/documents/47a39d15a8ab4059b47f05b8466d67d1?download=f7ed95c90e5e4cc3be264f4768d04b03", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-06-24T18:20:53.402718+03:00", 
          "id": "47a39d15a8ab4059b47f05b8466d67d1", 
          "dateModified": "2017-06-24T18:20:53.402757+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "tendererAction": "Умови виправлено", 
      "tendererActionDate": "2017-06-24T18:20:54.024040+03:00", 
      "dateSubmitted": "2017-06-24T18:20:51.791104+03:00", 
      "complaintID": "UA-2017-06-24-000001.1", 
      "date": "2017-06-24T18:20:54.032045+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "767b8633d3a74e46b7e3c8ef54d4de80", 
      "dateAccepted": "2017-06-24T18:20:52.844840+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2017-06-24T18:20:51.898617+03:00", 
      "dateSubmitted": "2017-06-24T18:20:51.511158+03:00", 
      "complaintID": "UA-2017-06-24-000001.2", 
      "date": "2017-06-24T18:20:52.114105+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "cab64a913eb84cf583687006871866bb"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2017-06-24T18:20:53.710443+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2017-06-24T18:20:52.975732+03:00", 
      "dateSubmitted": "2017-06-24T18:20:51.596712+03:00", 
      "complaintID": "UA-2017-06-24-000001.3", 
      "date": "2017-06-24T18:20:53.719619+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "870016d83d3143b586ceee63b85eff3c"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2017-06-24T18:20:52.575099+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2017-06-24T18:20:52.214097+03:00", 
      "dateAnswered": "2017-06-24T18:20:52.001831+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-06-24T18:20:51.685054+03:00", 
      "complaintID": "UA-2017-06-24-000001.4", 
      "date": "2017-06-24T18:20:52.582725+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "984265576f314bc9b50635c0de51fcbf"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-06-24T18:20:53.857723+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2017-06-24T18:20:53.857757+03:00", 
      "dateAccepted": "2017-06-24T18:20:53.109034+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-06-24T18:20:52.322672+03:00", 
      "complaintID": "UA-2017-06-24-000001.5", 
      "date": "2017-06-24T18:20:53.865958+03:00", 
      "type": "complaint", 
      "id": "5e659e181b1442778a78f11972dda36c"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2017-06-24T18:20:54.340109+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2017-06-24T18:20:54.182244+03:00", 
      "dateAccepted": "2017-06-24T18:20:53.250465+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2017-06-24T18:20:52.440138+03:00", 
      "complaintID": "UA-2017-06-24-000001.6", 
      "date": "2017-06-24T18:20:54.348199+03:00", 
      "type": "complaint", 
      "id": "b7d665a5db5043888c9ed5b3c346d221"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2017-06-24T18:20:54.662927+03:00", 
      "complaintID": "UA-2017-06-24-000001.7", 
      "date": "2017-06-24T18:20:54.671510+03:00", 
      "type": "claim", 
      "id": "aedc841a8d294fd581da3e048ce520d0"
    }
  ]
}

