POST /api/2.3/tenders/d5f01806d85143458795cbd133b0e667/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1055
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "selfQualified": true, 
    "value": {
      "amount": 500
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/d5f01806d85143458795cbd133b0e667/bids/b94deeb4edae4cdb8e6571b1b455abfb
{
  "access": {
    "token": "cf643c97d1f84f4487a651ad8d5e11da"
  }, 
  "data": {
    "status": "active", 
    "selfEligible": true, 
    "id": "b94deeb4edae4cdb8e6571b1b455abfb", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-06-24T18:20:57.097741+03:00", 
    "selfQualified": true
  }
}

