PATCH /api/2.3/tenders/d5f01806d85143458795cbd133b0e667?acc_token=f945406a1ac44cff8f49754d54f658fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "auctionPeriod": {
      "shouldStartAfter": "2017-07-10T00:00:00+03:00"
    }, 
    "tenderID": "UA-2017-06-24-000001", 
    "tenderPeriod": {
      "startDate": "2017-06-24T18:20:55.794009+03:00", 
      "endDate": "2017-07-09T18:21:05.949685+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-14T18:20:40.467711+03:00", 
          "endDate": "2017-08-13T18:20:40.467766+03:00"
        }, 
        "id": "bc5e1e48639541f1b57b9678a4085991", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "complaintPeriod": {
      "startDate": "2017-06-24T18:20:55.794009+03:00", 
      "endDate": "2017-07-05T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2017-06-24T18:20:55.831226+03:00", 
    "next_check": "2017-07-09T18:21:05.949685+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2017-06-24T18:20:55.794009+03:00", 
      "clarificationsUntil": "2017-07-04T18:21:05.949685+03:00", 
      "endDate": "2017-06-29T18:21:05.949685+03:00", 
      "invalidationDate": "2017-06-24T18:20:56.203702+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2017-06-24T18:20:56.207572+03:00", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "id": "d5f01806d85143458795cbd133b0e667", 
    "awardCriteria": "lowestCost"
  }
}

