PATCH /api/2.3/tenders/d5f01806d85143458795cbd133b0e667/contracts/a3c517f48e2f4c2d89324d8fd55ae025?acc_token=f945406a1ac44cff8f49754d54f658fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 118
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "period": {
      "startDate": "2017-06-24T18:20:59.048973+03:00", 
      "endDate": "2018-06-24T18:20:59.049021+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-14T18:20:40.467711+03:00", 
          "endDate": "2017-08-13T18:20:40.467766+03:00"
        }, 
        "id": "bc5e1e48639541f1b57b9678a4085991", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2017-06-24T18:20:59.048973+03:00", 
      "endDate": "2018-06-24T18:20:59.049021+03:00"
    }, 
    "dateSigned": "2017-06-24T18:20:58.879418+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardID": "593a1685fa504843abe3759a4a6f0c79", 
    "id": "a3c517f48e2f4c2d89324d8fd55ae025", 
    "contractID": "UA-2017-06-24-000001-1"
  }
}

