PATCH /api/2.3/tenders/d5f01806d85143458795cbd133b0e667?acc_token=f945406a1ac44cff8f49754d54f658fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

